// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCdeMcs4AO3DqadDMhmm3R6EcyiVVQFM',
    appId: '1:430164599159:web:3c2e00c089afcc7dcdc172',
    messagingSenderId: '430164599159',
    projectId: 'armessenger-7e803',
    authDomain: 'armessenger-7e803.firebaseapp.com',
    storageBucket: 'armessenger-7e803.firebasestorage.app',
    measurementId: 'G-P0K5XKMBD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq3zRgITvWMA9asfxIXUKBYK6KxOwaJAk',
    appId: '1:430164599159:android:cddee3e51293e7b3cdc172',
    messagingSenderId: '430164599159',
    projectId: 'armessenger-7e803',
    storageBucket: 'armessenger-7e803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2ZiCfcy6En1Ew7VT8WGDMsh9navNWaY',
    appId: '1:430164599159:ios:fe35e8cb25c950edcdc172',
    messagingSenderId: '430164599159',
    projectId: 'armessenger-7e803',
    storageBucket: 'armessenger-7e803.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu2ZiCfcy6En1Ew7VT8WGDMsh9navNWaY',
    appId: '1:430164599159:ios:fe35e8cb25c950edcdc172',
    messagingSenderId: '430164599159',
    projectId: 'armessenger-7e803',
    storageBucket: 'armessenger-7e803.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnCdeMcs4AO3DqadDMhmm3R6EcyiVVQFM',
    appId: '1:430164599159:web:d0e601cf268b5630cdc172',
    messagingSenderId: '430164599159',
    projectId: 'armessenger-7e803',
    authDomain: 'armessenger-7e803.firebaseapp.com',
    storageBucket: 'armessenger-7e803.firebasestorage.app',
    measurementId: 'G-HRR4KRT2KC',
  );
}
